### ISSUE TITLE
what if is this else for?

### ISSUE THREAD

**Issue by chad3814** [codebyzeb/wordleguesser#1]
https://github.com/codebyzeb/wordleguesser/blob/07a7841986c522e9b826e48efe3caef84943a5f1/wordle.py#L83-L90

I'm not a huge python person, so I was rewriting your code into javascript, since that's what I know best. Unfortunately I don't understand which `if` this `else` references, it's at the same level as the `for` loop.

**Comment by codebyzeb** [comment]
Great question! This is a special construction in python which I only learned about when writing this actually. Basically, the "else" block is only run if the "for" block exits properly. If the "break" is run, the "else" block won't run. You could rewrite this as:

```python
orange_or_green_double_letters_before = False
for j in range(5):
    if j != i and guess[i] == guess[j] and response[j] != "b": # if double letters and other occurrence is not black
        if not letter in self.banned_letters[i]:
            self.banned_letters[i] += letter
        orange_or_green_double_letters_before = True
if not orange_or_green_double_letters_before:
    for j in range(5):
        if not letter in self.banned_letters[j]:
            self.banned_letters[j] += letter
```

**Comment by chad3814** [comment]
Thank you so much!
